export const items = {

};

export const abilities: any = {
    0xFFFF: "Ability Code",
    0: "Attack Up +[HUDTEXT:VALUE_NUM ]%",
    1: "Attack Up +[HUDTEXT:VALUE_NUM ]%",
    2: "Attack Up +[HUDTEXT:VALUE_NUM ]%",
    3: "Defense Up +[HUDTEXT:VALUE_NUM ]%",
    4: "Defense Up +[HUDTEXT:VALUE_NUM ]%",
    5: "Defense Up +[HUDTEXT:VALUE_NUM ]%",
    6: "E-Save +[HUDTEXT:VALUE_NUM ]%",
    7: "E-Save +[HUDTEXT:VALUE_NUM ]%",
    8: "E-Save +[HUDTEXT:VALUE_NUM ]%",
    9: "E-Convert +[HUDTEXT:VALUE_NUM ]%",
    10: "E-Convert +[HUDTEXT:VALUE_NUM ]%",
    11: "E-Convert +[HUDTEXT:VALUE_NUM ]%",
    12: "E-Convert Range +[HUDTEXT:VALUE_NUM ]%",
    13: "E-Convert Range +[HUDTEXT:VALUE_NUM ]%",
    14: "E-Convert Range +[HUDTEXT:VALUE_NUM ]%",
    15: "Sync Heal +[HUDTEXT:DECTEN_NUM ]%",
    16: "Sync Heal +[HUDTEXT:DECTEN_NUM ]%",
    17: "Sync Heal +[HUDTEXT:DECTEN_NUM ]%",
    18: "Call Lock +[HUDTEXT:DECTEN_NUM ] sec",
    19: "Call Lock +[HUDTEXT:DECTEN_NUM ] sec",
    20: "Call Lock +[HUDTEXT:DECTEN_NUM ] sec",
    21: "Super Armor Alpha",
    22: "Super Armor Omega",
    23: "Chain Boost +[HUDTEXT:DECHUN_NUM ]m",
    24: "Chain Boost +[HUDTEXT:DECHUN_NUM ]m",
    25: "Chain Boost +[HUDTEXT:DECHUN_NUM ]m",
    26: "Berserk Mode +[HUDTEXT:VALUE_NUM ]%",
    27: "Berserk Mode +[HUDTEXT:VALUE_NUM ]%",
    28: "Berserk Mode +[HUDTEXT:VALUE_NUM ]%",
    29: "Critical Rate +[HUDTEXT:VALUE_NUM ]%",
    30: "Critical Rate +[HUDTEXT:VALUE_NUM ]%",
    31: "Critical Rate +[HUDTEXT:VALUE_NUM ]%",
    32: "Critical Damage +[HUDTEXT:VALUE_NUM ]%",
    33: "Critical Damage +[HUDTEXT:VALUE_NUM ]%",
    34: "Critical Damage +[HUDTEXT:VALUE_NUM ]%",
    35: "Perfect Call E-Heal +[HUDTEXT:VALUE_NUM ]%",
    36: "Perfect Call E-Heal +[HUDTEXT:VALUE_NUM ]%",
    37: "Perfect Call E-Heal +[HUDTEXT:VALUE_NUM ]%",
    38: "Item Drop Rate +[HUDTEXT:VALUE_NUM ]%",
    39: "Item Drop Rate +[HUDTEXT:VALUE_NUM ]%",
    40: "Item Drop Rate +[HUDTEXT:VALUE_NUM ]%",
    41: "Gene Code Absorb +[HUDTEXT:VALUE_NUM ]%",
    42: "Gene Code Absorb +[HUDTEXT:VALUE_NUM ]%",
    43: "Gene Code Absorb +[HUDTEXT:VALUE_NUM ]%",
    44: "Speed Boost +[HUDTEXT:VALUE_NUM ]%",
    45: "Speed Boost +[HUDTEXT:VALUE_NUM ]%",
    46: "Speed Boost +[HUDTEXT:VALUE_NUM ]%",
    47: "Legion Speed Boost +[HUDTEXT:VALUE_NUM ]%",
    48: "Legion Speed Boost +[HUDTEXT:VALUE_NUM ]%",
    49: "Legion Speed Boost +[HUDTEXT:VALUE_NUM ]%",
    50: "Red Matter Removal +[HUDTEXT:VALUE_NUM ]%",
    51: "Red Matter Removal +[HUDTEXT:VALUE_NUM ]%",
    52: "Red Matter Removal +[HUDTEXT:VALUE_NUM ]%",
    53: "Call Burst +[HUDTEXT:VALUE_NUM ]%",
    54: "Call Burst +[HUDTEXT:VALUE_NUM ]%",
    55: "Call Burst +[HUDTEXT:VALUE_NUM ]%",
    56: "Self Destruct +[HUDTEXT:VALUE_NUM ]%",
    57: "Self Destruct +[HUDTEXT:VALUE_NUM ]%",
    58: "Self Destruct +[HUDTEXT:VALUE_NUM ]%",
    59: "Quick Cooldown +[HUDTEXT:VALUE_NUM ]%",
    60: "Quick Cooldown +[HUDTEXT:VALUE_NUM ]%",
    61: "Quick Cooldown +[HUDTEXT:VALUE_NUM ]%",
    62: "Auto-Evade +[HUDTEXT:VALUE_NUM ]%",
    63: "Auto-Evade +[HUDTEXT:VALUE_NUM ]%",
    64: "Auto-Evade +[HUDTEXT:VALUE_NUM ]%",
    65: "Slow Attack +[HUDTEXT:VALUE_NUM ]%",
    66: "Slow Attack +[HUDTEXT:VALUE_NUM ]%",
    67: "Slow Attack +[HUDTEXT:VALUE_NUM ]%",
    68: "Chimera Analyzer",
    69: "Auto-Sync Attack",
    70: "Legion Rush",
    71: "Parry Attack",
    72: "Anti-Trip",
    73: "Anti-Decibel",
    74: "Anti-Slime",
    75: "Anti-Paralyze",
    76: "Anti-Freeze",
    77: "Anti-Flame",
    78: "Anti-Stun",
    79: "Anti-Poison",
    80: "Auto-Collect",
    81: "Fortitude",
    82: "Effect Spread",
    83: "Auto-Call",
    84: "Auto-Medic",
    85: "Auto-Heal",
    86: "Auto-Heal +",
    87: "Auto-Heal ++"
}

export const subabilities: any = {
    0: "None",
    1: "Attack Up +[HUDTEXT:VALUE_NUM ]%",
    2: "Defense Up +[HUDTEXT:VALUE_NUM ]%",
    3: "E-Save +[HUDTEXT:VALUE_NUM ]%",
    4: "E-Convert +[HUDTEXT:VALUE_NUM ]%",
    5: "E-Convert Range +[HUDTEXT:VALUE_NUM ]%",
    6: "Sync Heal +[HUDTEXT:DECTEN_NUM ]%",
    7: "Call Lock +[HUDTEXT:DECTEN_NUM ] sec",
    8: "Super Armor Alpha",
    9: "Super Armor Omega",
    10: "Chain Boost +[HUDTEXT:DECHUN_NUM ]m",
    11: "Berserk Mode +[HUDTEXT:VALUE_NUM ]%",
    12: "Critical Rate +[HUDTEXT:VALUE_NUM ]%",
    13: "Critical Damage +[HUDTEXT:VALUE_NUM ]%",
    14: "Perfect Call E-Heal +[HUDTEXT:VALUE_NUM ]%",
    15: "Item Drop Rate +[HUDTEXT:VALUE_NUM ]%",
    16: "Gene Code Absorb +[HUDTEXT:VALUE_NUM ]%",
    17: "Speed Boost +[HUDTEXT:VALUE_NUM ]%",
    18: "Legion Speed Boost +[HUDTEXT:VALUE_NUM ]%",
    19: "Red Matter Removal +[HUDTEXT:VALUE_NUM ]%",
    20: "Call Burst +[HUDTEXT:VALUE_NUM ]%",
    21: "Self Destruct +[HUDTEXT:VALUE_NUM ]%",
    22: "Quick Cooldown +[HUDTEXT:VALUE_NUM ]%",
    23: "Auto-Evade +[HUDTEXT:VALUE_NUM ]%",
    24: "Slow Attack +[HUDTEXT:VALUE_NUM ]%",
    25: "Chimera Analyzer",
    26: "Auto-Sync Attack",
    27: "Legion Rush",
    28: "Parry Attack",
    29: "Anti-Trip",
    30: "Anti-Decibel",
    31: "Anti-Slime",
    32: "Anti-Paralyze",
    33: "Anti-Freeze",
    34: "Anti-Flame",
    35: "Anti-Stun",
    36: "Anti-Poison",
    37: "Auto-Collect",
    38: "Fortitude",
    39: "Effect Spread",
    40: "Auto-Call",
    41: "Auto-Medic",
    42: "Auto-Heal"
}

export function getAbility(id: number, subability=false, value?:number) {
    if (!abilities[id] || (subability && !subabilities[id])) return "None";

    if (value === undefined) {
        // no value
        if (subability) {
            return subabilities[id].split("+")[0];
        } else {
            return abilities[id]
                .replace("[HUDTEXT:VALUE_NUM ]", abilityNum[id])
                .replace("[HUDTEXT:DECTEN_NUM ]", abilityNum[id] / 10)
                .replace("[HUDTEXT:DECHUN_NUM ]", abilityNum[id] / 100)
        }
    }

    return (subability ? subabilities[id] : abilities[id])
        .replace("[HUDTEXT:VALUE_NUM ]", value)
        .replace("[HUDTEXT:DECTEN_NUM ]", abilityNum[id] / 10)
        .replace("[HUDTEXT:DECHUN_NUM ]", value / 100)
}

const abilityNum: any = {
    0:  5,
    1:  15,
    2:  25,
    3:  5,
    4:  15,
    5:  25,
    6:  6,
    7:  18,
    8:  36,
    9:  5,
    10: 15,
    11: 30,
    12: 100,
    13: 300,
    14: 600,
    15: 4,
    16: 10,
    17: 20,
    18: 15,
    19: 45,
    20: 90,
    21: 1,
    22: 1,
    23: 120,
    24: 300,
    25: 500,
    26: 14,
    27: 30,
    28: 60,
    29: 2,
    30: 6,
    31: 12,
    32: 40,
    33: 100,
    34: 200,
    35: 25,
    36: 60,
    37: 100,
    38: 3,
    39: 9,
    40: 18,
    41: 5,
    42: 15,
    43: 30,
    44: 4,
    45: 9,
    46: 18,
    47: 5,
    48: 15,
    49: 30,
    50: 10,
    51: 30,
    52: 60,
    53: 30,
    54: 80,
    55: 150,
    56: 240,
    57: 600,
    58: 900,
    59: 8,
    60: 18,
    61: 35,
    62: 8,
    63: 18,
    64: 36,
    65: 2,
    66: 6,
    67: 10,
    68: 1,
    69: 1,
    70: 1,
    71: 1,
    72: 1,
    73: 1,
    74: 1,
    75: 1,
    76: 1,
    77: 1,
    78: 1,
    79: 1,
    80: 1,
    81: 1,
    82: 1,
    83: 1,
    84: 1,
    85: 1,
    86: 3,
    87: 6
}

export const enemies: any = {

};